language: node_js
node_js:
- '5'
script:
- chmod +x dist_verifier.sh
 - ./dist_verifier.sh
deploy:
  - provider: releases
    api_key:
      secure: mobW3qI1QOMN6dZSbQRP3rUkEp3WnoUuaWL+Xwcmtb5Y8brV4ecVUG2/vUs3JP4dnAoPu/Pwo0TJ/3uK0r0sNjFdGnGCRAAPAjdJyPBoPFOGjvp4cO2Gt6qnHexE62getW84ZZwMj+DjUji1D4/uIlkzejuCVl5RIM/3iWTuQUMw5Byi71a4jK3F4lyu4ISsv7DhwyEnSfQadx7BPsLP1+jzfVTnMJcMNCER0XsESfmhnG2+xT8nJciyeGMnzUVM7A+HMD0Lu7DeCWk/7awkrG+OphQ8mYa7TPBRziwZw+rJiM6+E/P3+nWjOyneov58KTJ/3DrFMjSaqvftcUbAu2ItERGzuJWib8+LyB55TtHQdnwxPrVMtrNXjQL+73Oz535x2HcoFNu+KzlNzGLo2o5RHi4yRUuVPSNLDpRgj4R7/peJd0DIwY+QSFn5tRgUXZAnga8j/Y6dncRJEwTdWnGDiBgCzzOPnIDL96TbSRLgkIOr9TY4Y4zI9nOw74IIo2/UB0tcKXHBxrkFclFdnwc0zbjU+F5E4oo11KA/Dl3NBsqYY5el43aj+Uy96b9ue9F5ky8d9tc+0rP9O3Cs2oX7DdXOduqp6cop95miV+ZYU0A3VYGvee2ATkwvHBT3Ys/d4WroyBHWohkmP0+OH+7VY9Q7PE4UEyAzwDwVIrI=
    file: dist/*
    file_glob: true
    skip_cleanup: 'true'
    on:
      branch: master
      tags: true
  - provider: npm
    api_key:
        secure: Ef/+cTKV1OHTYrl+87PoRKQO689fMpR2fbRCWs0xBktcSqmaz95aSz4aAgilh6z2yLDuJpJ2/1+Zo9W1zGkvPZP6HkYKiaXJnaovIQkaKvL/1FMxVgRbUkE0VWeSXZV05Zcl/gpiVfnqhIPzoDwTXKtyEwqtKIaOO0nIT4eIxbr+EY6H1OMqED8sSPGoHTEj5Qx0BMaZINGZP8XTWYz7X0OiIVpu7XRyPRbr/ldm2VZzQviAUZXd7Mioo3WSy0Xe1ruIhBz6teKzndQzWkUJKTtCGfw9ani20HEOs4jb8wqNo7KHOcMOYCIV6QLWLXoTm6GnwuAxpUNqZswjL+K5aQ8lPzp8wJ/Pm8PgBICb7aSWRuP82aYnQ7hPKQV15A0CLICNvJasKd3pnq6IHDS70YcNrPklEXaxYvnrW4QBT+IgSRxkSIZOppLgEUbrh9krwdpzFjbz55XYj85wCgLIOUcyQJ4oLFK2LV1CItbzw4a5vRiMzMWINlyXG2uFSrVOUVO3M3geasZTZuE8RU3fuKg9SO8qM55reJUNK/Ut+dC43qoiwdHGnyxlPCTTfIjsMDrCcIJ2oqvPZX92+O5uBNi0S7Jg5aVltMw3Ox6Ofm3IdsBHoySSaejgIT+9m5PT2LfcllJkl0xhJOhplGImJYe970V0Usmz4vifwlfJq4I=
    email: mac89@hotmail.com
    skip_cleanup: 'true'
    on:
      branch: master
      tags: true